import 'package:thingsboard_app/thingsboard_client.dart';

/// App-side page-key holders.
///
/// The new autogenerated client exposes flat method parameters instead of query
/// objects. Where a query object still exists in the client it is typed against the
/// handwritten enums/ids that the barrel hides (so it is unusable), and the app's
/// pagination framework (`PageKeyController<P>`) needs a single key object anyway.
/// These lightweight holders preserve that key shape; the datasources decompose them
/// into the controllers' flat params. All referenced types (`TimePageLink`, `PageLink`,
/// `AlarmSearchStatus`, `AlarmSeverity`, `AlarmId`, `UserId`, `EntityId`) resolve to the
/// built_value versions the rest of the app uses.
class AlarmQueryV2 {
  AlarmQueryV2(
    this.pageLink, {
    this.affectedEntityId,
    this.typeList,
    this.statusList,
    this.severityList,
    this.assigneeId,
  });

  EntityId? affectedEntityId;
  TimePageLink pageLink;
  List<String>? typeList;
  List<AlarmSearchStatus>? statusList;
  List<AlarmSeverity>? severityList;
  UserId? assigneeId;
}

class AlarmCommentsQuery {
  const AlarmCommentsQuery({required this.pageLink, required this.id});

  final PageLink pageLink;
  final AlarmId id;
}

class UsersAssignQuery {
  const UsersAssignQuery({required this.pageLink, required this.id});

  final PageLink pageLink;
  final AlarmId id;
}
