
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'wifi_network.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'wifi_network.g.dart';

@freezed
 abstract  class WifiNetwork with _$WifiNetwork {
const    factory WifiNetwork({
    required String ssid,
    required int rssi,
    required int channel,
   // required Uint8List bssid,
    required String auth,
    @Default('') String password,
  }) = _WifiNetwork;

  factory WifiNetwork.fromJson(Map<String, Object?> json) => _$WifiNetworkFromJson(json);
}