import 'package:thingsboard_app/thingsboard_client.dart';

/// Converts the new autogenerated client's per-type `built_value` page-data objects
/// (`PageDataAlarmInfo`, `PageDataUserInfo`, …) into the generic `PageData<T>` the
/// app's pagination framework consumes. Pass the `built_value` getters directly.
PageData<T> toPageData<T>(
  Iterable<T>? data,
  int? totalPages,
  int? totalElements,
  bool? hasNext,
) {
  return PageData<T>(
    data?.toList() ?? <T>[],
    totalPages ?? 0,
    totalElements ?? 0,
    hasNext ?? false,
  );
}
