# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    Dir.chdir("..")
    Dir.chdir("..")
    sh("fvm flutter test -r expanded --coverage")
  end

  desc "Build "
  lane :build do |options|
    Dir.chdir("..")
    # Building with Flutter
    sh("fvm", "flutter", "build", "apk",
    "--build-name=" + options[:version],
    "--build-number", options[:build_number],
    "--no-tree-shake-icons")
  end

  desc "Build QA env"
  lane :buildQA do |options|
      Dir.chdir("..")
      # Building with Flutter
      sh("fvm", "flutter", "build", "apk",
      "--build-name=" + options[:version],
      "--build-number", options[:build_number],
      "--dart-define-from-file=env/qa.env",
      "--no-tree-shake-icons")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
